stages:
  - install
  - test
  - quality
  - deploy

default:
  interruptible: true

workflow:
  rules:
    # For merge requests, create a pipeline.
    - if: '$CI_MERGE_REQUEST_IID'
    # For `master` branch, create a pipeline (this includes on schedules, pushes, merges, etc.).
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

include:
  - local: .gitlab/ci/install.gitlab-ci.yml
  - local: .gitlab/ci/test.gitlab-ci.yml
  - local: .gitlab/ci/quality.gitlab-ci.yml
  - local: .gitlab/ci/deploy.gitlab-ci.yml
