build-image:
  extends: .docker
  stage: deploy
  needs:
    - sonar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
  script:
    - scripts/build_image.sh
    - docker tag api:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE
  only:
    refs:
      - master
