install:
  extends: .node
  stage: install
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - node_modules
      - ~/.cache
  before_script:
    - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
    - npm config set "//npm.fontawesome.com/:_authToken" ${FONTAWESOME_NPM_AUTH_TOKEN}
  script:
    - yarn install --frozen-lockfile
