install:
  extends: .node
  stage: install
  cache:
    policy: push
  before_script:
    - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
    - npm config set "//npm.fontawesome.com/:_authToken" ${FONTAWESOME_NPM_AUTH_TOKEN}
  script:
    - yarn install --frozen-lockfile
