sonarcloud:
  stage: sonarqube
  needs:
    - lint
    - check-types
    - unit-test
    - e2e-test
    - test-docker-image
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - node_modules
  script:
    - sonar-scanner
